lab4b:	main.c structs.c dialog.c utils.c views.c models.c timing.c balance.c
	gcc -o lab4b main.c structs.c dialog.c utils.c views.c models.c timing.c balance.c -g -lreadline
	valgrind --leak-check=full ./lab4b

start: 
	valgrind --leak-check=full ./lab4b
